# Generated by Django 3.2.9 on 2021-12-09 11:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام شرکت')),
                ('phone', models.PositiveIntegerField(error_messages={'unique': 'این شماره تلفن قبلا وارد شده است'}, help_text='شماره تلفن خود را با 10 رقم وارد کنید. مثل= 9386938466', unique=True, verbose_name='شماره تلفن')),
                ('phone2', models.PositiveIntegerField(blank=True, error_messages={'unique': 'این شماره تلفن قبلا وارد شده است'}, help_text='شماره تلفن خود را با 10 رقم وارد کنید. مثل= 9386938466', null=True, unique=True, verbose_name='شماره تلفن دوم')),
                ('address', models.TextField(max_length=600, verbose_name='ادرس شرکت')),
            ],
            options={
                'verbose_name': 'شرکت',
                'verbose_name_plural': 'شرکت',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'این نام قبلا وارد شده است'}, max_length=50, unique=True, verbose_name='گروه')),
                ('number', models.IntegerField(error_messages={'unique': 'این شماره گروه قبلا وارد شده است'}, help_text='شماره گروه سه رقمی را وارد کنید', unique=True, verbose_name='شماره گروه')),
            ],
            options={
                'verbose_name': 'گروه',
                'verbose_name_plural': 'گروه',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default='default.jpg', upload_to='profile_images', verbose_name='عکس')),
                ('national_code', models.PositiveIntegerField(error_messages={'unique': 'این کد ملی قبلا ثبت شده است'}, help_text='لطفا کد ملی  را وارد کنید', unique=True, verbose_name='کدملی')),
                ('age', models.PositiveIntegerField(verbose_name='سن')),
                ('evidence', models.CharField(choices=[('1', 'زیردیپلم'), ('2', 'دیپلم'), ('3', 'فوق دیپلم'), ('4', 'لیسانس'), ('5', 'بالاتر از لیسانس')], default='4', max_length=1, verbose_name='مدرک تحصیلی')),
                ('phone', models.PositiveIntegerField(error_messages={'unique': 'این شماره تلفن قبلا وارد شده است'}, help_text='شماره تلفن خود را با 10 رقم وارد کنید. مثل= 9386938466', unique=True, verbose_name='شماره تلفن')),
                ('phone2', models.PositiveIntegerField(blank=True, error_messages={'unique': 'این شماره تلفن قبلا وارد شده است'}, help_text='شماره تلفن خود را با 10 رقم وارد کنید. مثل= 9386938466', null=True, unique=True, verbose_name='شماره تلفن دوم')),
                ('address', models.TextField(blank=True, max_length=600, null=True, verbose_name='آدرس')),
                ('post', models.CharField(choices=[('1', 'مدیر'), ('2', 'انبار دار'), ('3', 'مراجعه کننده'), ('4', 'راننده')], default='4', max_length=1, verbose_name='سمت')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل',
            },
        ),
        migrations.CreateModel(
            name='SelectWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام انبار')),
            ],
            options={
                'verbose_name': 'انتخاب انبار',
                'verbose_name_plural': 'انتخاب انبار',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'این نام قبلا وارد شده است'}, max_length=50, unique=True, verbose_name='واحد')),
            ],
            options={
                'verbose_name': 'واحد',
                'verbose_name_plural': 'واحد',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'این نام قبلا وارد شده است'}, max_length=50, unique=True, verbose_name='نام انبار')),
                ('possibilities', models.TextField(max_length=600, verbose_name='امکانات')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.company', verbose_name='نام شرکت')),
            ],
            options={
                'verbose_name': 'انبار',
                'verbose_name_plural': 'انبار',
            },
        ),
        migrations.CreateModel(
            name='WarehouseHandling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان انبار گردانی')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ شروع')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('comment', models.TextField(blank=True, max_length=1000, null=True, verbose_name='توضیحات')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.warehouse', verbose_name='انتخاب انبار')),
            ],
            options={
                'verbose_name': 'انبار گردانی',
                'verbose_name_plural': 'انبار گردانی',
            },
        ),
        migrations.CreateModel(
            name='Requestgoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_warehousekeeper', models.CharField(blank=True, max_length=15, verbose_name='انبار دار')),
                ('goods_name', models.CharField(max_length=100, verbose_name='کالا')),
                ('value', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='مقدار')),
                ('result', models.CharField(blank=True, choices=[('1', 'رد'), ('2', 'قبول')], max_length=1, null=True, verbose_name='نتیجه درخواست')),
                ('profile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.profile', verbose_name='درخواست دهنده')),
            ],
            options={
                'verbose_name': 'درخواست کالا',
                'verbose_name_plural': 'درخواست کالا',
            },
        ),
        migrations.CreateModel(
            name='RegistrationOfGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'این نام قبلا وارد شده است'}, max_length=30, unique=True, verbose_name='نام کالا')),
                ('code', models.CharField(error_messages={'unique': 'این کد قبلا وارد شده است'}, help_text='برای تولید کد کالا عدد 1 را وارد کنید تا کد کالا به صورت اتوماتیک ساخته شود.', max_length=10, unique=True, verbose_name='کد')),
                ('unit', models.CharField(max_length=50, verbose_name='واحد')),
                ('location', models.CharField(max_length=50, verbose_name='محل استقرار')),
                ('value', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='مقدار اولیه')),
                ('min_value', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='حداقل موجودی')),
                ('max_value', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='حداکثر موجودی')),
                ('expiration', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.group', verbose_name='انتخاب گروه کالا')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.warehouse', verbose_name='انتخاب انبار')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالا',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام محل استقرار')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.warehouse', verbose_name='نام انبار')),
            ],
            options={
                'verbose_name': 'محل استقرار',
                'verbose_name_plural': 'محل استقرار',
            },
        ),
        migrations.CreateModel(
            name='ExitGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_warehousekeeper', models.CharField(blank=True, max_length=15, verbose_name='نام انبار دار')),
                ('goods_name', models.CharField(max_length=100, verbose_name='کالا')),
                ('value', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='مقدار')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ')),
                ('driver_receive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_receive', to='MyApp.profile', verbose_name='راننده')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to='MyApp.profile', verbose_name='دریافت کننده')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.warehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'خروج کالا',
                'verbose_name_plural': 'خروج کالا',
            },
        ),
        migrations.CreateModel(
            name='EntryGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_warehousekeeper', models.CharField(blank=True, max_length=15, verbose_name='نام انبار دار')),
                ('goods_name', models.CharField(max_length=100, verbose_name='نام کالا')),
                ('value', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='مقدار')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ ورود')),
                ('driver_send', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_send', to='MyApp.profile', verbose_name='راننده')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to='MyApp.profile', verbose_name='ارسال کننده')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.warehouse', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'ورود کالا',
                'verbose_name_plural': 'ورود کالا',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.profile', verbose_name='مدیر'),
        ),
    ]
