# Generated by Django 3.2.9 on 2021-12-10 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_auto_20211209_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrygoods',
            options={'ordering': ('warehouse__name', 'date'), 'verbose_name': 'ورود کالا', 'verbose_name_plural': 'ورود کالا'},
        ),
        migrations.AlterModelOptions(
            name='exitgoods',
            options={'ordering': ('warehouse__name', 'date'), 'verbose_name': 'خروج کالا', 'verbose_name_plural': 'خروج کالا'},
        ),
        migrations.AlterModelOptions(
            name='requestgoods',
            options={'ordering': ('profile__user__username', 'result'), 'verbose_name': 'درخواست کالا', 'verbose_name_plural': 'درخواست کالا'},
        ),
        migrations.AlterModelOptions(
            name='warehousehandling',
            options={'ordering': ('warehouse__name', 'start_date'), 'verbose_name': 'انبار گردانی', 'verbose_name_plural': 'انبار گردانی'},
        ),
    ]
