# Generated by Django 3.2.9 on 2021-12-23 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_alter_exitgoods_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exitgoods',
            options={'ordering': ('warehouse__name', '-date'), 'verbose_name': 'خروج کالا', 'verbose_name_plural': 'خروج کالا'},
        ),
    ]
