# Generated by Django 3.2.9 on 2021-12-25 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_alter_exitgoods_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectwarehouse',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.warehouse', verbose_name='نام انبار'),
        ),
    ]
