# Generated by Django 3.2.9 on 2021-12-25 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_alter_registrationofgoods_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationofgoods',
            name='code',
            field=models.CharField(error_messages={'unique': 'این کد قبلا وارد شده است'}, help_text='برای تولید خودکار کد کالا، رقم 1 را وارد کنید.', max_length=15, unique=True, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='registrationofgoods',
            name='location',
            field=models.ForeignKey(help_text='<p style="color:yellow"><span style="color:red">توجه= </span>محل استقرار انتخاب شده باید متعلق به انبار انتخاب شده باشد.</p>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.location', verbose_name='محل استقرار'),
        ),
    ]
