# Generated by Django 3.2.9 on 2021-12-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0012_auto_20211225_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationofgoods',
            name='name',
            field=models.CharField(max_length=30, verbose_name='نام کالا'),
        ),
    ]
