# Generated by Django 3.2.9 on 2021-12-28 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyApp', '0014_alter_registrationofgoods_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrygoods',
            name='goods_name',
        ),
        migrations.RemoveField(
            model_name='entrygoods',
            name='name_warehousekeeper',
        ),
        migrations.RemoveField(
            model_name='exitgoods',
            name='goods_name',
        ),
        migrations.RemoveField(
            model_name='exitgoods',
            name='name_warehousekeeper',
        ),
        migrations.RemoveField(
            model_name='requestgoods',
            name='name_warehousekeeper',
        ),
        migrations.AddField(
            model_name='entrygoods',
            name='registrationOfGoods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.registrationofgoods', verbose_name='نام کالا'),
        ),
        migrations.AddField(
            model_name='entrygoods',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='انبار دار'),
        ),
        migrations.AddField(
            model_name='exitgoods',
            name='registrationOfGoods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.registrationofgoods', verbose_name='نام کالا'),
        ),
        migrations.AddField(
            model_name='exitgoods',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='انبار دار'),
        ),
        migrations.AddField(
            model_name='requestgoods',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='انبار دار'),
        ),
        migrations.AlterField(
            model_name='registrationofgoods',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام کالا'),
        ),
    ]
