# Generated by Django 3.2.9 on 2021-12-29 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0015_auto_20211228_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationofgoods',
            name='location',
            field=models.ForeignKey(help_text='<p style="color:green"><span style="color:red">توجه= </span>محل استقرار انتخاب شده باید متعلق به انبار انتخاب شده باشد.</p>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.location', verbose_name='محل استقرار'),
        ),
    ]
