# Generated by Django 3.2.9 on 2021-12-30 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyApp', '0016_alter_registrationofgoods_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrygoods',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='انبار دار'),
        ),
    ]
