# Generated by Django 3.2.9 on 2021-12-30 23:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0017_alter_entrygoods_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestgoods',
            options={'ordering': ('profile__user__username', '-date', 'result'), 'verbose_name': 'درخواست کالا', 'verbose_name_plural': 'درخواست کالا'},
        ),
        migrations.AddField(
            model_name='requestgoods',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ'),
        ),
    ]
