# Generated by Django 3.2.9 on 2021-12-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0018_auto_20211231_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestgoods',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ درخواست'),
        ),
    ]
