# Generated by Django 3.2.9 on 2021-12-31 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0019_alter_requestgoods_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestgoods',
            name='goods_name',
        ),
        migrations.AddField(
            model_name='requestgoods',
            name='goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.registrationofgoods', verbose_name='کالا'),
        ),
    ]
