# Generated by Django 3.2.9 on 2022-01-03 12:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0020_auto_20211231_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationofgoods',
            options={'ordering': ('warehouse__name', 'location__name'), 'verbose_name': 'ثبت کالا', 'verbose_name_plural': 'ثبت کالا'},
        ),
        migrations.RemoveField(
            model_name='registrationofgoods',
            name='code',
        ),
        migrations.RemoveField(
            model_name='registrationofgoods',
            name='group',
        ),
        migrations.RemoveField(
            model_name='registrationofgoods',
            name='name',
        ),
        migrations.RemoveField(
            model_name='registrationofgoods',
            name='unit',
        ),
        migrations.AlterField(
            model_name='entrygoods',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ورود'),
        ),
        migrations.AlterField(
            model_name='exitgoods',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ خروج'),
        ),
        migrations.AlterField(
            model_name='exitgoods',
            name='id',
            field=models.PositiveIntegerField(error_messages={'unique': 'این شناسه قبلا وارد شده است'}, help_text='حداکثر 10 رقم', primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='شناسه خروج'),
        ),
        migrations.AlterField(
            model_name='requestgoods',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست'),
        ),
        migrations.CreateModel(
            name='SerialGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(error_messages={'unique': 'این سریال قبلا وارد شده است'}, max_length=20, unique=True)),
                ('exitGoods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.exitgoods', verbose_name='خروج کالا')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'این نام قبلا وارد شده است'}, max_length=50, unique=True, verbose_name='نام کالا')),
                ('code', models.CharField(error_messages={'unique': 'این کد قبلا وارد شده است'}, help_text='برای تولید خودکار کد کالا، رقم 1 را وارد کنید.', max_length=10, unique=True, verbose_name='کد')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.group', verbose_name='انتخاب گروه کالا')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.unit', verbose_name='واحد')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالا',
                'ordering': ('code',),
            },
        ),
        migrations.AddField(
            model_name='registrationofgoods',
            name='goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.goods', verbose_name='کالا'),
        ),
        migrations.AlterField(
            model_name='requestgoods',
            name='goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.goods', verbose_name='کالا'),
        ),
    ]
