# Generated by Django 3.2.9 on 2022-01-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0021_auto_20220103_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ('code',), 'verbose_name': 'تعریف اولیه کالا', 'verbose_name_plural': 'تعریف اولیه کالا'},
        ),
        migrations.AlterModelOptions(
            name='serialgoods',
            options={'ordering': ('serial',), 'verbose_name': 'سریال خروج', 'verbose_name_plural': 'سریال خروج'},
        ),
        migrations.AlterField(
            model_name='entrygoods',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ ورود'),
        ),
        migrations.AlterField(
            model_name='exitgoods',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ خروج'),
        ),
        migrations.AlterField(
            model_name='requestgoods',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ درخواست'),
        ),
    ]
