# Generated by Django 3.2.9 on 2022-01-07 16:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0022_auto_20220105_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitgoods',
            name='id',
            field=models.PositiveIntegerField(error_messages={'unique': 'این شناسه قبلا وارد شده است'}, help_text='حداکثر 10 رقم', primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999999999, 'عدد وارد شده باید حداکثر دارای ده رقم باشد!')], verbose_name='شناسه خروج'),
        ),
        migrations.AlterField(
            model_name='registrationofgoods',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.location', verbose_name='محل استقرار'),
        ),
        migrations.AlterField(
            model_name='serialgoods',
            name='serial',
            field=models.CharField(error_messages={'unique': 'این سریال قبلا وارد شده است'}, max_length=40, unique=True),
        ),
    ]
