# Generated by Django 3.2.9 on 2022-01-08 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0023_auto_20220107_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestgoods',
            name='comment',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='غلت رد شدن'),
        ),
        migrations.AddField(
            model_name='requestgoods',
            name='serial',
            field=models.PositiveIntegerField(blank=True, help_text='حداکثر 10 رقم', null=True, validators=[django.core.validators.MaxValueValidator(9999999999, 'کد رهگیری وارد شده باید حداکثر دارای ده رقم باشد!')], verbose_name='کد رهگیری'),
        ),
        migrations.AlterField(
            model_name='serialgoods',
            name='serial',
            field=models.CharField(error_messages={'unique': 'این سریال قبلا وارد شده است'}, max_length=40, unique=True, verbose_name='سریال کالا'),
        ),
    ]
