# Generated by Django 3.2.9 on 2022-01-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0024_auto_20220108_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestgoods',
            name='comment',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='علت رد شدن'),
        ),
    ]
