# Generated by Django 3.2.9 on 2022-01-09 13:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0026_auto_20220108_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrygoods',
            name='time',
        ),
        migrations.RemoveField(
            model_name='exitgoods',
            name='time',
        ),
        migrations.AlterField(
            model_name='entrygoods',
            name='id',
            field=models.PositiveIntegerField(error_messages={'unique': 'این شناسه قبلا وارد شده است'}, help_text='حداکثر 10 رقم', primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999999999, 'عدد وارد شده باید حداکثر دارای ده رقم باشد!')], verbose_name='شناسه ورود'),
        ),
        migrations.CreateModel(
            name='SerialGoods_ENG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(error_messages={'unique': 'این سریال قبلا وارد شده است'}, max_length=40, unique=True, verbose_name='سریال کالا')),
                ('entryGoods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MyApp.entrygoods', verbose_name='ورود کالا')),
            ],
            options={
                'verbose_name': 'سریال ورود',
                'verbose_name_plural': 'سریال ورود',
                'ordering': ('serial',),
            },
        ),
    ]
