# Generated by Django 3.2.9 on 2022-01-09 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0027_auto_20220109_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrygoods',
            name='SerialForDriver',
            field=models.CharField(blank=True, max_length=50, verbose_name='سریال ورود راننده'),
        ),
        migrations.AddField(
            model_name='exitgoods',
            name='SerialForDriver',
            field=models.CharField(blank=True, max_length=50, verbose_name='سریال خروج راننده'),
        ),
        migrations.AlterField(
            model_name='entrygoods',
            name='id',
            field=models.PositiveIntegerField(error_messages={'unique': 'این شناسه قبلا وارد شده است'}, help_text='حداکثر 11 رقم', primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999999, 'عدد وارد شده باید حداکثر دارای 11 رقم باشد!')], verbose_name='شناسه ورود'),
        ),
        migrations.AlterField(
            model_name='exitgoods',
            name='id',
            field=models.PositiveIntegerField(error_messages={'unique': 'این شناسه قبلا وارد شده است'}, help_text='حداکثر 11 رقم', primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999999, 'عدد وارد شده باید حداکثر دارای 11 رقم باشد!')], verbose_name='شناسه خروج'),
        ),
    ]
