# Generated by Django 3.2.9 on 2022-01-10 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0028_auto_20220110_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitgoods',
            name='address',
            field=models.TextField(null=True, verbose_name='ادرس'),
        ),
        migrations.AddField(
            model_name='registrationofgoods',
            name='value_D',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='مقدار شمارش شده'),
        ),
        migrations.AddField(
            model_name='registrationofgoods',
            name='value_Diff',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='اختلاف مقدار'),
        ),
        migrations.AddField(
            model_name='requestgoods',
            name='address',
            field=models.TextField(null=True, verbose_name='ادرس'),
        ),
        migrations.AlterField(
            model_name='warehousehandling',
            name='start_date',
            field=models.DateField(verbose_name='تاریخ شروع'),
        ),
    ]
