# Generated by Django 3.2.9 on 2022-01-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0029_auto_20220110_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitgoods',
            name='address',
            field=models.TextField(default='exit', verbose_name='ادرس'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestgoods',
            name='address',
            field=models.TextField(verbose_name='ادرس'),
        ),
    ]
