# Generated by Django 3.2.9 on 2022-01-13 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0031_auto_20220113_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serialgoods',
            options={'ordering': ('serial',), 'verbose_name': 'سریال خروج کالا', 'verbose_name_plural': 'سریال خروج کالا'},
        ),
        migrations.AlterModelOptions(
            name='serialgoods_eng',
            options={'ordering': ('serial',), 'verbose_name': 'سریال ورود کالا', 'verbose_name_plural': 'سریال ورود کالا'},
        ),
    ]
