# Generated by Django 3.2.9 on 2022-01-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0032_auto_20220113_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitgoods',
            name='address',
            field=models.TextField(blank=True, verbose_name='ادرس'),
        ),
    ]
