# Generated by Django 3.2.9 on 2022-01-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0033_alter_exitgoods_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrygoods',
            name='SerialForDriver',
            field=models.CharField(blank=True, help_text='شماره رسید انبار = تاریخ امروز+شناسه کاربری راننده+شماره خروج راننده', max_length=10, verbose_name='شماره رسید انبار'),
        ),
        migrations.AlterField(
            model_name='entrygoods',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exitgoods',
            name='SerialForDriver',
            field=models.CharField(blank=True, help_text='شماره حواله انبار = تاریخ امروز+شناسه کاربری راننده+شماره خروج راننده', max_length=10, verbose_name='شماره حواله انبار'),
        ),
        migrations.AlterField(
            model_name='exitgoods',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='requestgoods',
            name='result',
            field=models.CharField(choices=[('2', 'رد'), ('1', 'قبول')], max_length=1, null=True, verbose_name='نتیجه درخواست'),
        ),
    ]
