# Generated by Django 3.2.9 on 2022-01-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0037_alter_requestgoods_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestgoods',
            name='serial',
            field=models.IntegerField(blank=True, error_messages={'unique': 'این شناسه قبلا وارد شده است'}, help_text='این شناسه توسط سرور تولید شده است.', null=True, unique=True, verbose_name='کد رهگیری(شناسه خروج)'),
        ),
    ]
