# Generated by Django 3.2.9 on 2022-01-20 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0039_alter_requestgoods_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitgoods',
            name='driver_receive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_receive', to='MyApp.profile', verbose_name='راننده'),
        ),
    ]
