# Generated by Django 3.2.9 on 2022-02-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0045_alter_exitgoods_driver_receive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrygoods',
            name='SerialForDriver',
            field=models.CharField(blank=True, help_text='شماره رسید انبار = تاریخ امروز+شناسه کاربری راننده+شماره ورود راننده', max_length=10, verbose_name='شماره رسید انبار'),
        ),
    ]
